on: [push]

jobs: 
#    build_terraform_docker:
#        runs-on: self-hosted
#        name: Build Terraform
#        steps: 
#            - name: Checkout
#              uses: actions/checkout@v4
#            - name: Set up Docker Buildx
#              uses: docker/setup-buildx-action@v3
#            - name: Build and export
#              uses: docker/build-push-action@v5
#              with:
#                context: ./.github/workflows/openstack/
#                file: ./.github/workflows/openstack/Dockerfile
#                tags: github-terraform-docker:latest
#                outputs: type=docker,dest=/tmp/github-terraform-docker.tar
#            - name: Upload Docker Image
#              uses: actions/upload-artifact@v4
#              with:
#                name: github-terraform-docker
#                path: /tmp/github-terraform-docker.tar
    run_terraform:
        runs-on: self-hosted
#        needs: build_terraform_docker
        container:
          image: localhost:5000/github-terraform-docker:latest
          env: 
            TF_VAR_user: ${{ secrets.OS_USERNAME }}
            TF_VAR_application_credential_id: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
            TF_VAR_application_credential_secret: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
            TF_VAR_ssh_access_key: ${{ secrets.OS_SSH_KEY }}
            TF_VAR_os_auth_region: ${{ secrets.OS_AUTH_REGION }}
            TF_VAR_os_auth_url: ${{ secrets.OS_AUTH_URL }}
            TF_VAR_os_project_domain_name: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
            TF_VAR_os_password: ${{ secrets.OS_PASSWORD }}
        steps:
            - name: Run Terraform
              run: |
                cd terraform
                terraform init
                terraform plan
                terraform apply -auto-approve
                terraform destroy -auto-approve

#    destroy_terraform:
#        runs-on: self-hosted
#        needs: run_terraform
#        name: Terraform Destroy
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v4
#            - name: Run Terraform Destroy
#              run: terraform destroy -auto-approve 