name: testsuite

on:
  push:
    branches:
      - "*"
      - '!docs'
    tags-ignore:
      - "*"
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-testsuite
  cancel-in-progress: true

jobs:
  testsuite:
    env:
      PERL_USE_UNSAFE_INC: 1
      CPANEL_BIN_PATH: /usr/local/cpanel/3rdparty/bin
      CPANEL_PERL: /usr/local/cpanel/3rdparty/perl/536/bin/perl
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: cpanelos/perl-compiler:perl-v5.36.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
	
      - name: Setup PATH
        run: |
          echo $CPANEL_BIN_PATH >> $GITHUB_PATH;
          $CPANEL_PERL -MConfig -E 'say $Config{sitebin}'   >> $GITHUB_PATH
          $CPANEL_PERL -MConfig -E 'say $Config{vendorbin}' >> $GITHUB_PATH
      - run: perl -V
      - name: install Perl dependencies
        uses: perl-actions/install-with-cpm@v1.7
        with:
          sudo: false
          cpanfile: "t/cpanfile"
          args: "--with-all"
      - name: cpanel-setup
        run: /bin/bash t/cpanel-setup
      - name: which prove
        run: ls -l $(which prove)
      - run: perl -cw elevate-cpanel
      - name: Run tests
        run: prove -lv -It/lib t/*.t

